import { Anek_Malayalam } from "next/font/google";
import "./globals.css";

const Font  = Anek_Malayalam ({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Font.className}>{children}</body>
    </html>
  );
}
